### ISSUE TITLE
steam://connect

### ISSUE THREAD

**Issue by ghost** [JustOneMoreBlock/unturned-php-status#1]
Hey, I'm the dysentery guy from RocketMod forums. Do you have any idea what's going on with the connect to server button? When I click on mine and when I click on yours they both do "server not responding" no matter what.

 I noticed that SourceQuery calls to add +1 to the port number for connecting on RCON and I saw where you had set up the variable on line 83 in index.php. My connection was showing that it was connecting to my server on 25445 because of that so I tried just using $Port on line 144 instead and it popped up a window with the correct port but it still said server not responding.

That is the limit to ideas I had to fix the problem.

Great job on this btw. There's very little resources for someone with my limited skills to get their hands on a tool like this. Usually you just ask and people go "lul that's super easy do it yourself". So you're my hero. :P

**Comment by JustOneMoreBlock** [comment]
> Do you have any idea what's going on with the connect to server button? When I click on mine and when I click on yours they both do "server not responding" no matter what.

No idea. I've had the problem for ages then after an update; it started working again.

It uses your default port that you use to connect to your server. Then an additional port for the SourceQuery information. I just used basic math to add instead of defining the port.

Well, initially I based off my inspiration of Unturned.Rocks. However, he wasn't releasing his anytime soon. Therefore, I made my own.

**Comment by ghost** [comment]
You did good. And you used very clean code that someone like me can use to learn off of. 

I'm going to have to search why that steam url doesn't work. It's a very nice touch if it can work. 

I'm going to close this though, as it's not an issue with your work. I just didn't know an easier channel to contact you.
